### ISSUE TITLE
Include the full git history of DebOps

### ISSUE THREAD

**Issue by ypid** [AnotherKamila/bsdops#6]
Hi

I checked out the project quickly and noticed that you don’t have the git history of DebOps. It could be useful to do, git clone https://github.com/debops/debops.git; commit your patches to make it work for FreeBSD; git push to your fork.

I think this will make it easier for your to contribute patches back for example. It would also be possible with this approach to maintain a patch-set on top of upstream DebOps. This is how many Android related projects do it (using git rebase). Just some ideas.

**Comment by AnotherKamila** [comment]
Hi,

first of all, thanks for jumping in! It's really encouraging to see DebOps devs looking at this.

I am using [git subrepo](https://github.com/ingydotnet/git-subrepo/) to manage the debops repo within here. It's an alternative to `git submodule`. My "actual" fork of the DebOps repository is at https://github.com/anotherKamila/debops , and `git subrepo` extracts commits to the `debops` subdirectory into that fork. Therefore I don't need the whole history of DebOps here: I have it in https://github.com/anotherKamila/debops . I can use that to send patches upstream.

**Comment by ypid** [comment]
Your are welcome. Interesting, I will need to checkout subrepo.

At DebOps and other projects I know submodules and similar are preferred for transparency/audibility reasons. This way all the OpenPGP signatures would still be included. So people who already trust DebOps could review your patches on top of the DebOps code easily. I will checkout subrepo when I have time to see how they address this. Thanks! I am closing this now because you have addressed the issue in a way that I have to understand first ;-)

**Comment by AnotherKamila** [comment]
Signatures are a valid point. Long story short: As far as I understand `git subrepo`, two interesting things can happen with signatures:

* Commits to this repository: History from `debops` would get squashed into one commit, signed by me. Original GPG signatures would probably be lost. This is, however, not a big problem, as this repo is documentation/coordination/"getting started" only and I might even delete it in the future if I stop needing it (currently I need it as a workaround for #1).
* Commits to my AnotherKamila/debops fork: That is the actually interesting repo, as it is the one people should actually use and regularly pull from and check. It contains the full history of upstream debops, so signatures in it are okay. Commits extracted from this repo (bsdops) into AnotherKamila/debops would hopefully get my signature (I have to try that to be sure).
